Feat/config display
koesterlab/srptn pull request #2
Opened 2024-09-17 15:27 UTC by Dexnjn

# Content
This pull request contains the addition of a "fill" popover for the data_editor and validation for the config file in the ace_editor view as well as some minor fixes.

2024-09-20 13:29 UTC, johanneskoester approved these changes

2024-09-20 13:29 UTC, johanneskoester commented
@coderabbitai please review

2024-09-20 13:30 UTC, johanneskoester commented
@coderabbitai review

2024-09-20 13:32 UTC, johanneskoester commented
Let us wait for the AI review. From my side this looks good.

2024-09-22 20:56 UTC, Dexnjn commented on common/components/config_editor.py
> +                only_validation = True
Clearer this way 👍🏻

2024-09-22 21:08 UTC, Dexnjn commented on common/components/data_editor.py
> +
I could not trigger the warning through the interface but adding error handling is likely not a bad choice

2024-09-22 21:35 UTC, Dexnjn commented on common/components/config_editor.py
> +                else:
This should be caught in validate_input to keep generation and validation separate.

2024-09-22 21:41 UTC, Dexnjn commented on common/components/data_editor.py
> +
We handle this by disabling imports

2024-09-23 07:43 UTC, johanneskoester requested changes

2024-09-23 07:43 UTC, johanneskoester commented on common/components/ui_components.py
> +    unique_key = key + "-" + label.lower()
```suggestion
    unique_key = f"{key}-{label.lower()}"
```

2024-09-23 07:45 UTC, johanneskoester approved these changes

2024-09-23 07:53 UTC, merged