feat: adopt polars & enforce ruff linting
koesterlab/srptn pull request #3
Opened 2024-09-27 22:29 UTC by Dexnjn

# Content
This pull request contains the replacement of pandas with polars dataframes in the whole code base. 
Functions were replaced with equivalents where possible and type checks were added where necessary to ensure functionality.
Additionally, ruff linting was applied to all files to comply with the latest rules.

2025-01-17 18:16 UTC, Dexnjn commented on common/data/__init__.py
> +        return re.sub(r"/", "___", str(self))
Good suggestion!

2025-01-17 18:27 UTC, Dexnjn commented on common/utils/yaml_utils.py
> +        return float(value)
Good Change!

2025-01-17 18:52 UTC, Dexnjn commented on common/utils/yaml_utils.py
> +        return self.represent_scalar("tag:yaml.org,2002:str", value)
Good idea, I resolved it with temporary tagging for number typed inputs in scientific notation.

2025-01-17 19:03 UTC, Dexnjn commented on common/tmux.py
> +            history_limit=10000,
The libtmux documentation has the kill_session parameter, thus manually terminating an existing session is redundant

2025-01-20 16:24 UTC, johanneskoester requested changes
Impressive work! A few exemplary comments below which probably apply elsewhere as well.

2025-01-20 16:24 UTC, johanneskoester commented on common/data/entities/analysis.py
> +        instance.check()
Why not just `cls(url=details["url"], ...)`?

2025-01-20 16:24 UTC, johanneskoester commented on common/data/entities/analysis.py
> +        )
I would rather solve this with if/else. Abusing next for this purpose seems uncommon to me.

2025-01-20 16:24 UTC, johanneskoester commented on common/data/entities/analysis.py
> +                    st.text(log_file)
Are we sure that we want frontend code in the data backend?

2025-01-20 17:29 UTC, Dexnjn commented on common/data/entities/analysis.py
> +        instance.check()
I first implemented workflow management differently and this is a remnant.
Changed it to the standard cls(...)

2025-01-20 17:33 UTC, Dexnjn commented on common/data/entities/analysis.py
> +        )
I thought this would accomplish the task in a concise way. 
However if/else is likely easier to understand and maintain so I will change it.

2025-01-20 18:02 UTC, Dexnjn commented on common/data/entities/analysis.py
> +                    st.text(log_file)
True, especially this part should likely be a component ~"logs.py" similar to "entities.py" or part of the Analysis class.
With the component driven design we would avoid bloated and hard to maintain classes, so I will try to make the show function of Analysis look more like that of Dataset.

2025-01-22 14:59 UTC, Dexnjn commented on common/components/logs.py
> +        with st.container(height=450):
streamlits container does have the height parameter

2025-01-29 09:14 UTC, johanneskoester approved these changes

2025-01-29 09:15 UTC, merged